### ISSUE TITLE
Phantasm Loader uses invalid URL, therefore script doesn't load

### ISSUE THREAD

**Issue by RandomGuy-nobody** [ATrainz/main#2]
https://raw.githubusercontent.com/ATrainz/main/main/TSB.lua Invalid 404

Please Patch

**Comment by ATrainz** [comment]
> https://raw.githubusercontent.com/ATrainz/main/main/TSB.lua Invalid 404
> 
> Please Patch

Yielding Arts has hired a Former Synapse X Developer to join their team.
What this means for phantasm: It needs a better obfuscator, and it needs a rewrite.

Current scripts are detected on tsb including Infinite Yield, Infinite Yield Reborn, Dex and Hydroxide.
This was intentional, I took down TSB.lua.

This will not be fixed right now.
